Copy reference to features.names() instead of full copy, to avoid this repeated segfault:
#0  0xf6f6bb7c in memcpy () from /lib/libc.so.6
#1  0xf713e724 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_clone(std::allocator<char> const&, unsigned int) ()
   from /usr/lib/libstdc++.so.6
#2  0xf713f087 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libstdc++.so.6
#3  0xf72c08e3 in std::_Construct<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > (__p=0xf219f140, __value=Traceback (most recent call last):
  File "/usr/share/gdb/python/libstdcxx/v6/printers.py", line 469, in to_string
    return self.val['_M_dataplus']['_M_p'].string (encoding, length = len)
RuntimeError: Error reading string from inferior: Input/output error

[...]

#7  0xf72d2e73 in std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::vector (this=0xf695d004, __x=std::vector of length 0, capacity 256)
    at /usr/lib/gcc/x86_64-redhat-linux/4.1.2/../../../../include/c++/4.1.2/bits/stl_vector.h:234
#8  0xf72d1e37 in Ami::FeatureExpression::evaluate (this=0xf695d0ac, features=..., e=...) at FeatureExpression.cc:43
#9  0xf72c9e6b in Ami::EnvPlot::EnvPlot (this=0xf219eb20, p=@0xf695d248, features=..., cds=...) at EnvPlot.cc:48
#10 0xf72d52b6 in Ami::OperatorFactory::_extract (this=0xf695d1c4, p=@0xf695d248, input=..., output_cds=...) at OperatorFactory.cc:65
#11 0xf72d547b in Ami::OperatorFactory::deserialize (this=0xf695d1c4, p=@0xf695d248, input=..., output_cds=..., output_signature=1)
    at OperatorFactory.cc:82
#12 0xf72b22b2 in Ami::Analysis::Analysis (this=0xf2171b10, id=17, input=..., output=1, cds=..., cache=..., p=@0xf695d248) at Analysis.cc:28
#13 0xf735b49d in Ami::AnalysisFactory::configure (this=0xffffd158, id=17, msg=..., payload=0x80cb8ec "", cds=...) at AnalysisFactory.cc:125
#14 0xf72f4322 in Ami::Server::processIo (this=0x8087af8) at Server.cc:78
#15 0xf7287e46 in Ami::Poll::poll (this=0xffffd46c) at Poll.cc:189
#16 0xf7287eeb in Ami::Poll::routine (this=0xffffd46c) at Poll.cc:214
#17 0xf7289ac4 in Ami::TaskMainLoop (task=0x8073468) at Task.cc:157
#18 0xf7058832 in start_thread () from /lib/libpthread.so.0
#19 0xf6fcc4de in clone () from /lib/libc.so.6